<h2>Scopo del progetto</h2>
Il progetto knowledge nasce con l'obiettivo di implementare un social network data driven. L'idea alla base del progetto è quella di permetter agli utenti di postare notizie, messaggi, foto o altro (liberamente, senza schemi fissi) e di implementare all'interno del sistem aalgoritmmi che estraggano le informazioni salienti (grazie alla geolocalizzazione e al contenuto postato) e di mostrare all'utente che accede al servizio cosa accade in quel momento nella sua zona e quali utenti sono a lui vicini. 

<h2>Cosa abbiamo implementato</h2>
Per l'hackhaton abbiamo implementato un piccolo sistema di posting che tiene conto della localizzazione dell'utente al momento del post. L'utente puòvisualizzare cosa accade in un raggio predefinito (modificbile) rispetto alla sua posozione. Inoltre, abbiamo implementato una versione molto grezza di TF IDF per poter estrearre le parole che hanno più rilevanza rispetto ai POST localizzati attorno all'utente. In questo modo abbiamo cercato di enfatizzare quale dovrebbe essere il funzionamento finale del nostro progetto. (Ovviamente in 48 ore è impossibile implemenare algorimti complessi ma TF IDF già da una idea di cosa accade). Se il sistem aviene usato e vengono inserite molte notizie il comportamento emergente è quello di mostrare le parole più importanti data una posizione e un certo raggio. 
<h3>Chat localizzata</h3>
Oltre alla generazione delle notizie pià importanti per un dato luogo abbiamo implementato il SOLO login di una chat geolovalizzata. Questa chat dovrebbe permettere agli utenti in una data regione geografica di comunicare senza dover passare per sistemi tipo facebook o altro (aggiunta amici etc)
<h3>Implementazioni future</h3>
Sicuramente, la prima implementazione che contiamo di mandare in fase di produzione è quella di una testata giornalistica event driven in cui chi pubblica non dovrà preoccuparsi di partizionare le notizie. Sarà il sistema a fornire agli utenti lettori quelle di maggiore interesse per loro.
